// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKN8p3ODr1TPFYZsaGNJfksh5FPgFlWo',
    appId: '1:107767614847:web:b7bb1a38d61c8b81fe5e4a',
    messagingSenderId: '107767614847',
    projectId: 'bhagchal-d19c7',
    authDomain: 'bhagchal-d19c7.firebaseapp.com',
    databaseURL: 'https://bhagchal-d19c7-default-rtdb.firebaseio.com',
    storageBucket: 'bhagchal-d19c7.firebasestorage.app',
    measurementId: 'G-XWYQLEPXZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BMvZsyhUCDpy8ztOq5RzINl5TVQP9m8',
    appId: '1:107767614847:android:48f13c01f44fee44fe5e4a',
    messagingSenderId: '107767614847',
    projectId: 'bhagchal-d19c7',
    databaseURL: 'https://bhagchal-d19c7-default-rtdb.firebaseio.com',
    storageBucket: 'bhagchal-d19c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr77gQARRM403F-BZ4P1v5HGhiZCVRsTw',
    appId: '1:107767614847:ios:b34bcd7b134542abfe5e4a',
    messagingSenderId: '107767614847',
    projectId: 'bhagchal-d19c7',
    databaseURL: 'https://bhagchal-d19c7-default-rtdb.firebaseio.com',
    storageBucket: 'bhagchal-d19c7.firebasestorage.app',
    iosBundleId: 'com.example.bhagchal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr77gQARRM403F-BZ4P1v5HGhiZCVRsTw',
    appId: '1:107767614847:ios:b34bcd7b134542abfe5e4a',
    messagingSenderId: '107767614847',
    projectId: 'bhagchal-d19c7',
    databaseURL: 'https://bhagchal-d19c7-default-rtdb.firebaseio.com',
    storageBucket: 'bhagchal-d19c7.firebasestorage.app',
    iosBundleId: 'com.example.bhagchal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSKN8p3ODr1TPFYZsaGNJfksh5FPgFlWo',
    appId: '1:107767614847:web:73e59c2f898a60dbfe5e4a',
    messagingSenderId: '107767614847',
    projectId: 'bhagchal-d19c7',
    authDomain: 'bhagchal-d19c7.firebaseapp.com',
    databaseURL: 'https://bhagchal-d19c7-default-rtdb.firebaseio.com',
    storageBucket: 'bhagchal-d19c7.firebasestorage.app',
    measurementId: 'G-RY5HZXGTSM',
  );
}
